/**
 * @packageDocumentation
 * @module api.functional.group_orders.participants.items
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGroupOrderParticipant } from "../../../../structures/IGroupOrderParticipant";
import type { IOrderItemAdd } from "../../../../structures/IOrderItemAdd";
import type { IOrderItemUpdate } from "../../../../structures/IOrderItemUpdate";

/**
 * Add a wine to my enrollment
 * @controller GroupOrdersController.addOrderItem
 * @path POST /group-orders/participants/:participantId/items
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function addOrderItem(
  connection: IConnection,
  participantId: string,
  input: IOrderItemAdd,
): Promise<addOrderItem.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...addOrderItem.METADATA,
      template: addOrderItem.METADATA.path,
      path: addOrderItem.path(participantId),
    },
    input,
  );
}
export namespace addOrderItem {
  export type Input = IOrderItemAdd;
  export type Output = IGroupOrderParticipant;

  export const METADATA = {
    method: "POST",
    path: "/group-orders/participants/:participantId/items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (participantId: string) =>
    `/group-orders/participants/${encodeURIComponent(participantId?.toString() ?? "null")}/items`;
}

/**
 * Update quantity of an order item
 * @controller GroupOrdersController.updateOrderItem
 * @path PATCH /group-orders/participants/:participantId/items/:itemId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateOrderItem(
  connection: IConnection,
  participantId: string,
  itemId: string,
  input: IOrderItemUpdate,
): Promise<updateOrderItem.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateOrderItem.METADATA,
      template: updateOrderItem.METADATA.path,
      path: updateOrderItem.path(participantId, itemId),
    },
    input,
  );
}
export namespace updateOrderItem {
  export type Input = IOrderItemUpdate;
  export type Output = IGroupOrderParticipant;

  export const METADATA = {
    method: "PATCH",
    path: "/group-orders/participants/:participantId/items/:itemId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (participantId: string, itemId: string) =>
    `/group-orders/participants/${encodeURIComponent(participantId?.toString() ?? "null")}/items/${encodeURIComponent(itemId?.toString() ?? "null")}`;
}

/**
 * Remove an order item
 * @controller GroupOrdersController.removeOrderItem
 * @path DELETE /group-orders/participants/:participantId/items/:itemId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function removeOrderItem(
  connection: IConnection,
  participantId: string,
  itemId: string,
): Promise<removeOrderItem.Output> {
  return PlainFetcher.fetch(connection, {
    ...removeOrderItem.METADATA,
    template: removeOrderItem.METADATA.path,
    path: removeOrderItem.path(participantId, itemId),
  });
}
export namespace removeOrderItem {
  export type Output = IGroupOrderParticipant;

  export const METADATA = {
    method: "DELETE",
    path: "/group-orders/participants/:participantId/items/:itemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (participantId: string, itemId: string) =>
    `/group-orders/participants/${encodeURIComponent(participantId?.toString() ?? "null")}/items/${encodeURIComponent(itemId?.toString() ?? "null")}`;
}
