/**
 * @packageDocumentation
 * @module api.functional.group_orders.my
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as participations from "./participations";
