/**
 * API SDK — auto-generated by Nestia.
 *
 * Run `npm run generate-sdk` (or `nx run api:generate-sdk`) to regenerate
 * this library from the NestJS controllers.
 *
 * Until the first generation, re-export the shared types so the frontend
 * can already import from `@wine-order-app/api-sdk`.
 */
export * from '@wine-order-app/shared-types';
