/**
 * @packageDocumentation
 * @module api.functional.group_orders.summary
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGroupOrderSummary } from "../../../structures/IGroupOrderSummary";

/**
 * Get aggregated summary for a group order (supplier view)
 * @controller GroupOrdersController.getSummary
 * @path GET /group-orders/:id/summary
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getSummary(
  connection: IConnection,
  id: string,
): Promise<getSummary.Output> {
  return PlainFetcher.fetch(connection, {
    ...getSummary.METADATA,
    template: getSummary.METADATA.path,
    path: getSummary.path(id),
  });
}
export namespace getSummary {
  export type Output = IGroupOrderSummary;

  export const METADATA = {
    method: "GET",
    path: "/group-orders/:id/summary",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/group-orders/${encodeURIComponent(id?.toString() ?? "null")}/summary`;
}
