/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IAuthResponse } from "../../structures/IAuthResponse";
import type { IGoogleLoginRequest } from "../../structures/ILoginRequest";

/**
 * @controller AuthController.googleLogin
 * @path POST /auth/google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function googleLogin(
  connection: IConnection,
  input: IGoogleLoginRequest,
): Promise<googleLogin.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...googleLogin.METADATA,
      template: googleLogin.METADATA.path,
      path: googleLogin.path(),
    },
    input,
  );
}
export namespace googleLogin {
  export type Input = IGoogleLoginRequest;
  export type Output = IAuthResponse;

  export const METADATA = {
    method: "POST",
    path: "/auth/google",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/google";
}
