/**
 * @packageDocumentation
 * @module api.functional.group_orders.my.participations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGroupOrderParticipant } from "../../../../structures/IGroupOrderParticipant";

/**
 * Get the current user's enrollments
 * @controller GroupOrdersController.myParticipations
 * @path GET /group-orders/my/participations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function myParticipations(
  connection: IConnection,
): Promise<myParticipations.Output> {
  return PlainFetcher.fetch(connection, {
    ...myParticipations.METADATA,
    template: myParticipations.METADATA.path,
    path: myParticipations.path(),
  });
}
export namespace myParticipations {
  export type Output = IGroupOrderParticipant[];

  export const METADATA = {
    method: "GET",
    path: "/group-orders/my/participations",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/group-orders/my/participations";
}
