/**
 * @packageDocumentation
 * @module api.functional.group_orders.site
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGroupOrder } from "../../../structures/IGroupOrder";

/**
 * Get group orders for a specific site
 * @controller GroupOrdersController.findBySite
 * @path GET /group-orders/site/:siteId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findBySite(
  connection: IConnection,
  siteId: string,
): Promise<findBySite.Output> {
  return PlainFetcher.fetch(connection, {
    ...findBySite.METADATA,
    template: findBySite.METADATA.path,
    path: findBySite.path(siteId),
  });
}
export namespace findBySite {
  export type Output = IGroupOrder[];

  export const METADATA = {
    method: "GET",
    path: "/group-orders/site/:siteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (siteId: string) =>
    `/group-orders/site/${encodeURIComponent(siteId?.toString() ?? "null")}`;
}
