/**
 * @packageDocumentation
 * @module api.functional.group_orders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGroupOrder } from "../../structures/IGroupOrder";
import type { IGroupOrderCreate } from "../../structures/IGroupOrderCreate";
import type { IGroupOrderParticipant } from "../../structures/IGroupOrderParticipant";

export * as site from "./site";
export * as summary from "./summary";
export * as my from "./my";
export * as participants from "./participants";

/**
 * List all group orders, optionally filtered by status
 * @controller GroupOrdersController.findAll
 * @path GET /group-orders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
  status?: undefined | "open" | "closed" | "submitted" | "shipped",
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(status),
  });
}
export namespace findAll {
  export type Output = IGroupOrder[];

  export const METADATA = {
    method: "GET",
    path: "/group-orders",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    status: undefined | "open" | "closed" | "submitted" | "shipped",
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      status,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/group-orders";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * Get a single group order by id
 * @controller GroupOrdersController.findOne
 * @path GET /group-orders/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(id),
  });
}
export namespace findOne {
  export type Output = IGroupOrder;

  export const METADATA = {
    method: "GET",
    path: "/group-orders/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/group-orders/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Admin — open a new group order for a shipping site
 * @controller GroupOrdersController.create
 * @path POST /group-orders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: IGroupOrderCreate,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    input,
  );
}
export namespace create {
  export type Input = IGroupOrderCreate;
  export type Output = IGroupOrder;

  export const METADATA = {
    method: "POST",
    path: "/group-orders",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/group-orders";
}

/**
 * Admin — close a group order (no more modifications)
 * @controller GroupOrdersController.close
 * @path PATCH /group-orders/:id/close
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function close(
  connection: IConnection,
  id: string,
): Promise<close.Output> {
  return PlainFetcher.fetch(connection, {
    ...close.METADATA,
    template: close.METADATA.path,
    path: close.path(id),
  });
}
export namespace close {
  export type Output = IGroupOrder;

  export const METADATA = {
    method: "PATCH",
    path: "/group-orders/:id/close",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/group-orders/${encodeURIComponent(id?.toString() ?? "null")}/close`;
}

/**
 * Admin — submit a closed group order to supplier
 * @controller GroupOrdersController.submit
 * @path PATCH /group-orders/:id/submit
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function submit(
  connection: IConnection,
  id: string,
): Promise<submit.Output> {
  return PlainFetcher.fetch(connection, {
    ...submit.METADATA,
    template: submit.METADATA.path,
    path: submit.path(id),
  });
}
export namespace submit {
  export type Output = IGroupOrder;

  export const METADATA = {
    method: "PATCH",
    path: "/group-orders/:id/submit",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/group-orders/${encodeURIComponent(id?.toString() ?? "null")}/submit`;
}

/**
 * Admin — mark group order as shipped
 * @controller GroupOrdersController.ship
 * @path PATCH /group-orders/:id/ship
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function ship(
  connection: IConnection,
  id: string,
): Promise<ship.Output> {
  return PlainFetcher.fetch(connection, {
    ...ship.METADATA,
    template: ship.METADATA.path,
    path: ship.path(id),
  });
}
export namespace ship {
  export type Output = IGroupOrder;

  export const METADATA = {
    method: "PATCH",
    path: "/group-orders/:id/ship",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/group-orders/${encodeURIComponent(id?.toString() ?? "null")}/ship`;
}

/**
 * Enroll in a group order (copies cart → order items)
 * @controller GroupOrdersController.enroll
 * @path POST /group-orders/:id/enroll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function enroll(
  connection: IConnection,
  id: string,
): Promise<enroll.Output> {
  return PlainFetcher.fetch(connection, {
    ...enroll.METADATA,
    template: enroll.METADATA.path,
    path: enroll.path(id),
  });
}
export namespace enroll {
  export type Output = IGroupOrderParticipant;

  export const METADATA = {
    method: "POST",
    path: "/group-orders/:id/enroll",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/group-orders/${encodeURIComponent(id?.toString() ?? "null")}/enroll`;
}
