/**
 * @packageDocumentation
 * @module api.functional.shipping_sites.all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IShippingSite } from "../../../structures/IShippingSite";

/**
 * Admin — list all shipping sites including inactive
 * @controller ShippingSitesController.findAllAdmin
 * @path GET /shipping-sites/all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAllAdmin(
  connection: IConnection,
): Promise<findAllAdmin.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAllAdmin.METADATA,
    template: findAllAdmin.METADATA.path,
    path: findAllAdmin.path(),
  });
}
export namespace findAllAdmin {
  export type Output = IShippingSite[];

  export const METADATA = {
    method: "GET",
    path: "/shipping-sites/all",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shipping-sites/all";
}
