/**
 * @packageDocumentation
 * @module api.functional.wines
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IWine } from "../../structures/IWine";
import type { IWineCreate } from "../../structures/IWineCreate";
import type { IWineFilter } from "../../structures/IWineFilter";
import type { IWineListResponse } from "../../structures/IWineListResponse";
import type { IWineUpdate } from "../../structures/IWineUpdate";

/**
 * Public — browse the wine catalog with filters
 * @controller WinesController.findAll
 * @path GET /wines
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
  filter: IWineFilter,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(filter),
  });
}
export namespace findAll {
  export type Query = IWineFilter;
  export type Output = IWineListResponse;

  export const METADATA = {
    method: "GET",
    path: "/wines",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (filter: findAll.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(filter as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/wines";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * Public — get a single wine by id
 * @controller WinesController.findOne
 * @path GET /wines/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(id),
  });
}
export namespace findOne {
  export type Output = IWine;

  export const METADATA = {
    method: "GET",
    path: "/wines/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/wines/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Admin — create a wine
 * @controller WinesController.create
 * @path POST /wines
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: IWineCreate,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    input,
  );
}
export namespace create {
  export type Input = IWineCreate;
  export type Output = IWine;

  export const METADATA = {
    method: "POST",
    path: "/wines",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/wines";
}

/**
 * Admin — update a wine
 * @controller WinesController.update
 * @path PATCH /wines/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  input: IWineUpdate,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    input,
  );
}
export namespace update {
  export type Input = IWineUpdate;
  export type Output = IWine;

  export const METADATA = {
    method: "PATCH",
    path: "/wines/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/wines/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Admin — delete a wine
 * @controller WinesController.remove
 * @path DELETE /wines/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(id),
  });
}
export namespace remove {
  export const METADATA = {
    method: "DELETE",
    path: "/wines/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/wines/${encodeURIComponent(id?.toString() ?? "null")}`;
}
