/**
 * @packageDocumentation
 * @module api.functional.cart.items
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ICart } from "../../../structures/ICart";
import type { ICartItemAdd } from "../../../structures/ICartItemAdd";
import type { ICartItemUpdate } from "../../../structures/ICartItemUpdate";

/**
 * Add an item to cart (or increment quantity if it already exists)
 * @controller CartController.addItem
 * @path POST /cart/items
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function addItem(
  connection: IConnection,
  input: ICartItemAdd,
): Promise<addItem.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...addItem.METADATA,
      template: addItem.METADATA.path,
      path: addItem.path(),
    },
    input,
  );
}
export namespace addItem {
  export type Input = ICartItemAdd;
  export type Output = ICart;

  export const METADATA = {
    method: "POST",
    path: "/cart/items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/cart/items";
}

/**
 * Update quantity of a cart item
 * @controller CartController.updateItem
 * @path PATCH /cart/items/:itemId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateItem(
  connection: IConnection,
  itemId: string,
  input: ICartItemUpdate,
): Promise<updateItem.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateItem.METADATA,
      template: updateItem.METADATA.path,
      path: updateItem.path(itemId),
    },
    input,
  );
}
export namespace updateItem {
  export type Input = ICartItemUpdate;
  export type Output = ICart;

  export const METADATA = {
    method: "PATCH",
    path: "/cart/items/:itemId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (itemId: string) =>
    `/cart/items/${encodeURIComponent(itemId?.toString() ?? "null")}`;
}

/**
 * Remove an item from cart
 * @controller CartController.removeItem
 * @path DELETE /cart/items/:itemId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function removeItem(
  connection: IConnection,
  itemId: string,
): Promise<removeItem.Output> {
  return PlainFetcher.fetch(connection, {
    ...removeItem.METADATA,
    template: removeItem.METADATA.path,
    path: removeItem.path(itemId),
  });
}
export namespace removeItem {
  export type Output = ICart;

  export const METADATA = {
    method: "DELETE",
    path: "/cart/items/:itemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (itemId: string) =>
    `/cart/items/${encodeURIComponent(itemId?.toString() ?? "null")}`;
}
