/**
 * @packageDocumentation
 * @module api.functional.shipping_sites
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IShippingSite } from "../../structures/IShippingSite";
import type { IShippingSiteCreate } from "../../structures/IShippingSiteCreate";
import type { IShippingSiteUpdate } from "../../structures/IShippingSiteUpdate";

export * as all from "./all";

/**
 * Public — list active shipping sites
 * @controller ShippingSitesController.findAll
 * @path GET /shipping-sites
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = IShippingSite[];

  export const METADATA = {
    method: "GET",
    path: "/shipping-sites",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shipping-sites";
}

/**
 * Public — get a single shipping site
 * @controller ShippingSitesController.findOne
 * @path GET /shipping-sites/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(id),
  });
}
export namespace findOne {
  export type Output = IShippingSite;

  export const METADATA = {
    method: "GET",
    path: "/shipping-sites/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/shipping-sites/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Admin — create a shipping site
 * @controller ShippingSitesController.create
 * @path POST /shipping-sites
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: IShippingSiteCreate,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    input,
  );
}
export namespace create {
  export type Input = IShippingSiteCreate;
  export type Output = IShippingSite;

  export const METADATA = {
    method: "POST",
    path: "/shipping-sites",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/shipping-sites";
}

/**
 * Admin — update a shipping site
 * @controller ShippingSitesController.update
 * @path PATCH /shipping-sites/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  input: IShippingSiteUpdate,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    input,
  );
}
export namespace update {
  export type Input = IShippingSiteUpdate;
  export type Output = IShippingSite;

  export const METADATA = {
    method: "PATCH",
    path: "/shipping-sites/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/shipping-sites/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Admin — delete a shipping site
 * @controller ShippingSitesController.remove
 * @path DELETE /shipping-sites/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(id),
  });
}
export namespace remove {
  export const METADATA = {
    method: "DELETE",
    path: "/shipping-sites/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/shipping-sites/${encodeURIComponent(id?.toString() ?? "null")}`;
}
