/**
 * @packageDocumentation
 * @module api.functional.cart
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ICart } from "../../structures/ICart";

export * as items from "./items";

/**
 * Get the current user's cart
 * @controller CartController.getCart
 * @path GET /cart
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCart(
  connection: IConnection,
): Promise<getCart.Output> {
  return PlainFetcher.fetch(connection, {
    ...getCart.METADATA,
    template: getCart.METADATA.path,
    path: getCart.path(),
  });
}
export namespace getCart {
  export type Output = ICart;

  export const METADATA = {
    method: "GET",
    path: "/cart",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/cart";
}

/**
 * Clear all cart items
 * @controller CartController.clearCart
 * @path DELETE /cart
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function clearCart(connection: IConnection): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...clearCart.METADATA,
    template: clearCart.METADATA.path,
    path: clearCart.path(),
  });
}
export namespace clearCart {
  export const METADATA = {
    method: "DELETE",
    path: "/cart",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/cart";
}
